sudo: false
os:
- linux
language: node_js
node_js:
- node
script:
- npm install -g gulp
- gulp
after_success:
- npm run package
env:
  global:
    secure: QAM0xjbrfX2M2hEFpUR95vJM5o9Q9CkrkYPa2zNbKqRIqXFQ+++LHBTEj3uVCnewqN92Od4lyaYlmUOuSQhAPenp6FbU7sIwU556mDYHfkJeFYw6QqheiKPpe89Zdt6/TgB/v/Muzchl+ts2NI/JE1Lh7jgTn7jlQaGWkj/e5MVUQmYACu57Vd7BXA9m8PqZPhUQuHL0DnjeT/QeI4hS0o1H5Q1/14VRCJ120679v+EAACrwxVQ1ZUtMhja7r0q1CzotLtrzSRbgJ5laMiOkXtmYMqawiVwr1d098vUxgS3d27geH/oa1W/tDNKRDNzae0/4aQxokdM0ZXIJC/Ts2nGaD6Z6iqWDq2l279d/kkAOKZ4u829G4oO22V1bOxbFpqN08a3yFqpGSZvsP/Jukn1mUj325q+haC7CWqc29ycsgqB54FHVmS6mGB3rbUSXdH5eCzPylG/XXYuNCIQOGcDmH3K4CsXK9mhrBJV/wZhKPKn8HYtWC8a+2eN9B7wxxz3CRDPi7vmRtYF75x0mD7GBQhw1fwBXZVfIhhH1DJGZfl5pz10Iza+Mfgc3ga0CQjO+705DHZjIRD3RZb+9/dOcrXaOVMHUb4SFj3/ElbEpLzqRy0LuaEX5kCAOSQouNb2N5drW47U36C4gLgZnA8hwL0AcctoEg3d5oKA3mFQ=
deploy:
  provider: releases
  api_key:
    secure: Hhv03ZqEbvJj7XWHWBVFabYe6dYlQEbzvGjwCyz5g7EM9IIbCJrDRgixRlOH9TUK8NvwT2N820YHE5N94DpKG9rvQft1cC9y9r8HxinofFNqogjSqdKIaee3bXrYErwLaBXCNorgT9Vu9jFw83zd/5P/5IvnarCLenKfayAuLlgi8TfSUWFo/mwjTtjijdiANw+2wrdo0fZ0/zwVj+5oM78aoV7Ky+pg8B8osOHBvPcjNguGWJ8qXFjy2BeDbnDNW2aXE0m0u3DiY8TfQax+GAj9zAzY6eDwFsgtu/zg4oHE7S+TYfgCi21sd9rShHS9uIugWctkbMwhuTfrK3zAWyPQrp6kLYUzD/PNJXiUGPvR1D9W2ii7XGqmIsBPahdm2feVN3YKxbJ89qo35osV+k/Uf4fybzBbYia0L4cdZ1gjfV+1ZjkzYhmtNaYX7QCrPHXrxMD2nEKQF+YxkFAi+/Blvtts9detxfP/tKB9kM/35T+0yUYSMlgpC+/INb3JDwDG7PebApWda5T+9ypWVNAm0QYvNS/L3j1JEbNi2D5lfOevv5jrHzC8vXVNBmkV22Mx9JnBfsTAJsB/P86CuUH0Mtwu1sPKfCActFa+5Yleszv5nQNlxqT/Vk2u6EJfR1WRDltaTLVUDFRproCUyqmv10dK1VGuJji9FxfyRtk=
  file: "*.vsix"
  on:
    repo: smartether/vscode-lua
